---
- name: "Install Extra System Tools"
  become: true
  ansible.builtin.apt:
    name: "{{ wsl_env_extra_tools }}"
    state: present
  tags: better-shell-tools

- name: "Add Aliases to new tools"
  template:
    src: "wsl2/etc/bash_aliases.d/99-extra-tools.sh.j2"
    dest: /etc/bash_aliases.d/99-extra-tools.sh
    owner: root
    group: root
    mode: "0644"
  tags: better-shell-tools
