---
- name: "Check if gping is already installed"
  ansible.builtin.stat:
    path: /usr/local/bin/gping
  register: gping_bin
  tags: better-shell-tools

- name: "Install gping"
  when: not gping_bin.stat.exists
  block:
    - name: "Gping: Remove old azlux repository files"
      become: true
      ansible.builtin.file:
        path: "{{ azlux_item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/azlux.list
        - /usr/share/keyrings/azlux.gpg
      loop_control:
        loop_var: azlux_item

    - name: "Gping: Get latest release version"
      ansible.builtin.uri:
        url: https://api.github.com/repos/orf/gping/releases/latest
        return_content: yes
      register: gping_release
      changed_when: false

    - name: "Gping: Download gping binary"
      become: true
      ansible.builtin.get_url:
        url: "https://github.com/orf/gping/releases/download/{{ gping_release.json.tag_name }}/gping-Linux-musl-x86_64.tar.gz"
        dest: "/tmp/gping.tar.gz"
        mode: "0644"

    - name: "Gping: Create temp extraction directory"
      become: true
      ansible.builtin.file:
        path: /tmp/gping-extract
        state: directory
        mode: "0755"

    - name: "Gping: Extract and install gping"
      become: true
      ansible.builtin.shell:
        cmd: "tar -xzf /tmp/gping.tar.gz -C /tmp/gping-extract --strip-components=1 && install /tmp/gping-extract/gping /usr/local/bin/gping"

    - name: "Gping: Cleanup"
      ansible.builtin.file:
        path: "{{ cleanup_item }}"
        state: absent
      loop:
        - "/tmp/gping.tar.gz"
        - "/tmp/gping-extract"
      loop_control:
        loop_var: cleanup_item

  tags: better-shell-tools
