---
- name: "Install More Tools"
  ansible.builtin.include_tasks: extra-tools.yml
  tags: better-shell-tools

- name: "Install EZA"
  ansible.builtin.include_tasks: "install-{{ item }}.yml"
  with_items:
   - eza
   - gping
   - ripgrep
  tags: better-shell-tools
